grakn2 server clean

diff --git a/grakn-dist/src/grakn2 b/grakn-dist/src/grakn2
--- a/grakn-dist/src/grakn2
+++ b/grakn-dist/src/grakn2
@@ -17,6 +17,10 @@
 # You should have received a copy of the GNU General Public License
 # <http://www.gnu.org/licenses/gpl.txt>.
 
+# ================================================
+# global variables
+# ================================================
+
 # globals
 WAIT_INTERVAL_S=2
 
@@ -37,6 +41,9 @@ CASSANDRA_STARTUP_TIMEOUT_S=60
 # Redis globals
 REDIS_STARTUP_TIMEOUT_S=10
 
+# ================================================
+# common helper functions
+# ================================================
 update_classpath() {
   # Define CLASSPATH, exclude slf4j as we use logback
   for jar in "${GRAKN_HOME}"/services/lib/*.jar; do
@@ -50,9 +57,9 @@ update_classpath() {
   CLASSPATH="$CLASSPATH":"${GRAKN_HOME}"/services/grakn
 }
 
-# ========================
-# cassandra helpers
-# ========================
+# ================================================
+# cassandra helper functions
+# ================================================
 cassandra_start_cassandra() {
   "${GRAKN_HOME}"/services/cassandra/cassandra -p $CASSANDRA_PS > /dev/null 2>&1
   return $?
@@ -87,9 +94,30 @@ cassandra_wait_until_ready() {
   return 1
 }
 
-# ========================
-# redis helpers
-# ========================
+cassandra_stop_cassandra() {
+  echo -n "Stopping Cassandra..."
+  if [[ -e $CASSANDRA_PS ]]; then
+    pid=`cat $CASSANDRA_PS`
+    kill "$pid"
+    while kill -0 "$pid" 2>/dev/null; do
+        sleep 0.5
+    done
+    echo "SUCCESS"
+    return 0
+  else
+    echo "FAILED!" # unable to find PID
+    return 1
+  fi
+}
+
+cassandra_clean_cassandra() {
+  rm -rf db/cassandra
+  mkdir -p db/cassandra/data db/cassandra/commitlog db/cassandra/saved_caches
+}
+
+# ================================================
+# redis helper functions
+# ================================================
 redis_start_redis() {
   local redis_bin=""
   if [ "$(uname)" == "Darwin" ]; then
@@ -131,9 +159,39 @@ redis_wait_until_ready() {
   return 1
 }
 
-# ========================
-# grakn helpers
-# ========================
+redis_stop_redis() {
+  echo -n "Stopping Redis..."
+  local redis_bin=
+  if [ "$(uname)" == "Darwin" ]; then
+      redis_bin="redis-cli-osx"
+  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
+      redis_bin="redis-cli-linux"
+  fi
+  "${GRAKN_HOME}/services/redis/"$redis_bin shutdown
+  local status=$?
+  if [ $status -eq 0 ] ; then
+    echo "SUCCESS"
+  else
+    echo "FAILED!"
+  fi
+
+  return $status
+}
+
+redis_clean_redis() {
+  local redis_bin=
+  if [ "$(uname)" == "Darwin" ]; then
+      redis_bin="redis-cli-osx"
+  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
+      redis_bin="redis-cli-linux"
+  fi
+
+  "${GRAKN_HOME}/services/redis/"$redis_bin flushall
+}
+
+# ================================================
+# grakn helper functions
+# ================================================
 grakn_start_grakn() {
   local status=
   java -cp "${CLASSPATH}" -Dgrakn.dir="${GRAKN_HOME}/services" -Dgrakn.conf="${GRAKN_CONFIG}" \
@@ -167,6 +225,27 @@ grakn_wait_until_ready() {
   return 1
 }
 
+grakn_stop_grakn() {
+  echo -n "Stopping Grakn..."
+  if [[ -e "$GRAKN_PS" ]]; then
+    kill `cat $GRAKN_PS`
+    status_kill=$?
+    rm $GRAKN_PS
+    if [ $status_kill -eq 0 ] ; then
+      echo "SUCCESS"
+    else
+      echo "FAILED" # unable to kill
+    fi
+    return $status_kill
+  else
+    echo "FAILED!" # unable to find PID file
+    return 1
+  fi
+}
+
+# ================================================
+# command line helpers
+# ================================================
 grakn_server_start_cassandra() {
   cassandra_is_cassandra_running
   is_cassandra_running=$?
@@ -258,65 +337,13 @@ grakn_server_start_grakn() {
 }
 
 grakn_server_stop() {
-  grakn_server_stop_grakn() {
-    echo -n "Stopping Grakn..."
-    if [[ -e "$GRAKN_PS" ]]; then
-      kill `cat $GRAKN_PS`
-      status_kill=$?
-      rm $GRAKN_PS
-      if [ $status_kill -eq 0 ] ; then
-        echo "SUCCESS"
-      else
-        echo "FAILED" # unable to kill
-      fi
-      return $status_kill
-    else
-      echo "FAILED!" # unable to find PID file
-      return 1
-    fi
-  }
-  grakn_server_stop_redis() {
-    echo -n "Stopping Redis..."
-    local redis_bin=
-    if [ "$(uname)" == "Darwin" ]; then
-        redis_bin="redis-cli-osx"
-    elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
-        redis_bin="redis-cli-linux"
-    fi
-    "${GRAKN_HOME}/services/redis/"$redis_bin shutdown
-    local status=$?
-    if [ $status -eq 0 ] ; then
-      echo "SUCCESS"
-    else
-      echo "FAILED!"
-    fi
-
-    return $status
-  }
-
-  grakn_server_stop_cassandra() {
-    echo -n "Stopping Cassandra..."
-    if [[ -e $CASSANDRA_PS ]]; then
-      pid=`cat $CASSANDRA_PS`
-      kill "$pid"
-      while kill -0 "$pid" 2>/dev/null; do
-          sleep 0.5
-      done
-      echo "SUCCESS"
-      return 0
-    else
-      echo "FAILED!" # unable to find PID
-      return 1
-    fi
-  }
-
-  grakn_server_stop_grakn
+  grakn_stop_grakn
   status_grakn=$?
 
-  grakn_server_stop_redis
+  redis_stop_redis
   status_redis=$?
 
-  grakn_server_stop_cassandra
+  cassandra_stop_cassandra
   status_cassandra=$?
 
   if [ $status_grakn -eq 0 ] && [ $status_redis -eq 0 ] && [ $status_cassandra -eq 0 ] ; then
@@ -324,6 +351,10 @@ grakn_server_stop() {
   else
     return 1
   fi
+}
+
+grakn_clean_grakn() {
+  rm "${GRAKN_HOME}"/logs/*.log
 }
 
 # attempt to start grakn components. if one of them fails, abort everthing
@@ -358,7 +389,7 @@ grakn_server_start() {
   return $status
 }
 
-display_grakn_server_status() {
+grakn_server_status() {
   cassandra_is_cassandra_running
   if [ $? -eq 0 ] ; then
     echo "Casssandra: RUNNING"
@@ -381,15 +412,44 @@ display_grakn_server_status() {
   fi
 }
 
+# TODO
+# better to remove this functionality in production.
+# Having a very accessible full deletion functionality like this is dangerous
 grakn_server_clean() {
-  echo "clean"
+  cassandra_is_cassandra_running
+  local is_cassandra_running=$?
+
+  redis_is_redis_running
+  local is_redis_running=$?
+
+  grakn_is_grakn_running
+  local is_grakn_running=$?
+
+  if [ $is_cassandra_running -eq 0 ] || [ $is_redis_running -eq 0 ] || [ $is_grakn_running -eq 0 ] ; then
+    echo "Grakn is still running! Please shut down before performing a cleanup."
+  else
+    echo -n "Are you sure you want to delete all stored data and logs? [y/N] " >&2
+    read response
+    if [ "$response" != "y" -a "$response" != "Y" ]; then
+        echo "Response \"$response\" did not equal \"y\" or \"Y\".  Canceling clean operation." >&2
+        return 0
+    fi
+
+    cassandra_clean_cassandra
+
+    grakn_server_start_redis
+    redis_clean_redis
+    redis_stop_redis
+
+    grakn_clean_grakn
+  fi
 }
 
-display_version() {
+grakn_version() {
   echo "1.0"
 }
 
-display_help() {
+grakn_help() {
   echo "
 Usage:
 grakn COMMAND
@@ -437,20 +497,20 @@ case "$1" in
         # TODO: graceful termination failed. report failures
       ;;
       status)
-        display_grakn_server_status
+        grakn_server_status
       ;;
       clean)
         grakn_server_clean
       ;;
       *)
-        display_help
+        grakn_help
       ;;
     esac
   ;;
   version)
-    display_version
+    grakn_version
   ;;
   *|help)
-    display_help
+    grakn_help
   ;;
 esac
